### ISSUE TITLE
Match outputs with broom tidiers?

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/modeldb#20]
Just was taking a look at the kmeans tidier!

Would it make sense to match outputs up with the `broom` tidiers to the degree possible for consistency within tidyverse / db universe? Or to provide `augment()`, `glance()` and `tidy()` methods for database models?

**Comment by edgararuiz** [comment]
Yeah, that's a great idea.  Is there a spec I should look at?

**Comment by alexpghayes** [comment]
For an easy start I'd just copy what `tidy.lm()` and `tidy.kmeans()`, etc, do. I'm working on exporting tests for [`modeltests`](https://github.com/alexpghayes/modeltests) but it's messy at the moment. Hopefully will get cleaned up sometime over the summer, but progress is slow. There's also the [vignette](https://broom.tidyverse.org/articles/adding-tidiers.html) on adding new tidiers to `broom`.

**Comment by edgararuiz** [comment]
Fixed by 67bd599ab85255874cebf42d9ea97ba093162575
