### ISSUE TITLE
simple_kmeans_db() relies on a right join which is not supported by SQLite

### ISSUE THREAD

**Issue by klmedeiros** [tidymodels/modeldb#29]
When using `simple_kmeans_db()` with a database connection, it relies on a right join. However, right joins (and also full outer joins) are not supported in SQLite (see documentation [here](https://www.sqlite.org/omitted.html)), which is used to create the necessary query.

Error generated when attempting to use `simple_kmeans_db()` with a db con:
![image](https://user-images.githubusercontent.com/16199504/85155431-bbf33100-b226-11ea-80d7-15f0dacf3a96.png)

Query generated from same model (can see right join about halfway down):
![image](https://user-images.githubusercontent.com/16199504/85155728-1be9d780-b227-11ea-8630-988d5dd34680.png)

The code will need to be refactored likely to use a left join instead, as that's supported by SQLite. Alternatively, another SQL database engine could be attempted.

**Comment by juliasilge** [comment]
I definitely can reproduce this problem, and I think this means that `simple_kmeans_db()` probably never worked at all for SQLite? 😬
